# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: confluent
  labels:
    app: postgres-deployment
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/sambitbehera/PersistentVolumeK8s # Replace with your local directory path

---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: confluent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: confluent
  labels:
    app: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: confluent
  labels:
    app: postgres-deployment
spec:
  selector:
    app: postgres-deployment
  ports:
    - name: postgres-service-port
      protocol: TCP
      port: 5432
  type: LoadBalancer
  loadBalancerIP: ""
